print("Welcome to the Band Name Generator.")
city = input("What's the city you grew up in?\n")
print(city)
pet = input("What is the name of your pet?\n")
print(pet)
print("Your band name could be"+" "+ city +" "+ pet)